apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logs-collector
spec:
  selector:
    matchLabels:
      name: logs-collector
  template:
    metadata:
      labels:
        name: logs-collector
    spec:
      hostIPC: true
      hostPID: true
      hostNetwork: true
      containers:
      - name: logs-collector
        image: gcr.io/google-containers/toolbox 
        tty: true
        command:
        - /bin/bash
        - -c
        - |
          while true; do
            /bin/sh -c 'date "+%Y%m%d %H:%M:%S";  echo "conttrack -S: "; conntrack -S'
            sleep 15m
          done
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
        securityContext:
          privileged: true
