apiVersion: v1
kind: Pod
metadata:
  name: mylittlepod
spec:
  containers:
  - name: container1
    image: polinux/stress
    resources:
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]

