apiVersion: v1
kind: Pod
metadata:
 name: echo-server
spec:
  containers:
  - image: alpine
    command:
    - nc 
    - -v
    - -l
    - -p
    - "8888"
    - -s
    - 0.0.0.0
#    - "$(MY_IP)"
    env:
     - name: MY_IP
       valueFrom:
          fieldRef:
            fieldPath: status.podIP
    imagePullPolicy: Always
    name: echo-server
    resources:
      requests:
        cpu: 100m
