apiVersion: v1
kind: Pod
metadata:
 name: ping-host
spec:
  containers:
  - image: alpine
    command:
    - sh
    - -c
    - while true; do echo resolving; nslookup $host; echo pinging; date; nc -w 4 -v $host $port
      ; echo ---; sleep 2; done
    imagePullPolicy: Always
    name: echo-server
    env:
    - name: host
      value: www.google.com
    - name: port
      value: "443"
    resources:
      requests:
        cpu: 100m
