apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dualpod
  name: dualpod
spec:
  containers:
  - image: alpine
    command:
    - sh
    - -c
    - apk update; apk add iproute2; for i in $(seq 60); do ss -s ; sleep 5; done; sleep infinity
    name: ss-runner
    resources:
      requests:
        cpu: 100m
  - name: nginx
    image: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Never
