apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutateme
  labels:
    app: mutateme
webhooks:
  - name: mutateme.default.svc.cluster.local
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQUtmZmR3bkx6RHdhZU9zTlJ6RXJpTWN3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa04ySTRaakJsTVRNdFpESTBNUzAwWm1Vd0xXRmtNelF0T1RSa01qZGpOakpsWW1WbQpNQjRYRFRJd01EWXdNVEl5TWpNeU5Wb1hEVEkxTURVek1USXpNak15TlZvd0x6RXRNQ3NHQTFVRUF4TWtOMkk0ClpqQmxNVE10WkRJME1TMDBabVV3TFdGa016UXRPVFJrTWpkak5qSmxZbVZtTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBekZxVVVUZk4ybmdXZkdtVnBmK2pzYUpBZjAyN2ljL1VTYklubFpJYQpyRzlGNXpNZXpwT240Z1U5NlpDMEh5VnlxOUh0Zk1LRFczQkxlUDZ0L01OdmZlTlJjclhpTkdHQlJNdlZRTTVxCkFxdEI4dlQrZnl3dU5sMEdrUE9NTDQyeEVjL0pRamR5dzc5TEx4OEdRQW9iZmdaT0ZEVkg3YTd3TjJ5LzE4ZFcKWlFmZGx3VDc1cUVlVTB4ditiZXlQUXVKZFJyQ3UxVHlWeXJKTm81Rk1XR2VrWkZRQlVTb3YvTXpjYmRza3A1bApBVmw3cE1BSVEwN1BjS1cyL1dtVlNJTCtKMmtDUVBoMTU0NzQrTEtvWnJ0UDJCUkNZOUsvRjJhcDFadzZ0MGRwCmZFMjQrQU1yOEgrUXJPcEwyWkVjWHVGdnpmMXc4bUQzZnBFWkVKb3VpS2FGNVFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpiWVFzWVkrQUYxWHF4NmRIanUrRlhNQlkrMEVlN00zc2I2N0h4Tnp1dXBNdXJrbFRveUVPbnZEZ0s5SWozNWVnCjM1djFDL0hvSzdsSEU0VVJpNUJBT1hnRzBxR00vbncrS2M2MENqWENYT3k0TkFseEdONk1KTkFRS2ZvbmxvVjMKaDBSU1NFbkNRTkZ1MGVkSm81R1R0NFIyOXBPZjNEYjJvY0llRk5TUy9sUnY4NGhLZU52SXd5a1JJQjE1Y0tucgpUODN6cENxRERtVlFoWlU2dmxJVVYybm9nakZON1Btdi9mZmVIdDdMKzRnVVdSRjFHckpsRmtqZXd0Wi9uNUpFCkk0eG9FenJzbHR6bk9oK3FnaUdiQmNwOVNqUlJ4WTJ5V2tLZmtVMit4eFZHeXp0TDVXRkZvUlE1R2M3QUxOOG8KSUlxL1FSeThkSkZlWFVVMUV5eFQ5QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: mutateme
        namespace: default
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        mutateme: enabled

